### ISSUE TITLE
Truncated MIT license text

### ISSUE THREAD

**Issue by pombredanne** [Succo/emoji#1]
The word "permission" is missing
See https://github.com/Succo/wkttoorb/pull/1 for another example.
There could be more repos of yours subject to the same issue?

**Comment by pombredanne** [comment]
See also https://github.com/Succo/countrymoji/blob/master/License.txt

**Comment by jba** [comment]
At some time in the future, this is going to prevent the doc from being visible on pkg.go.dev.

**Comment by Succo** [comment]
Patched thanks

**Comment by jba** [comment]
The word "permission" is still missing at the current master: https://github.com/Succo/emoji/blob/f96f5c4523387c5758d05f5bc2f954ecea8d2a03/License.txt.

**Comment by Succo** [comment]
Indeed, but I belive it is now corrected https://github.com/Succo/emoji/blob/master/License.txt
